;;; jtsx-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jtsx.el

(autoload 'jtsx-jsx-mode "jtsx"
"Major mode extending `js-ts-mode'.

In addition to any hooks its parent mode might have run, this mode
runs the hook `jtsx-jsx-mode-hook', as the final or penultimate step
during initialization.

\\{jtsx-jsx-mode-map}" t)
(autoload 'jtsx-tsx-mode "jtsx"
"Major mode extending `tsx-ts-mode'.

In addition to any hooks its parent mode might have run, this mode
runs the hook `jtsx-tsx-mode-hook', as the final or penultimate step
during initialization.

\\{jtsx-tsx-mode-map}" t)
(autoload 'jtsx-typescript-mode "jtsx"
"Major mode extending `typescript-ts-mode'.

In addition to any hooks its parent mode might have run, this mode
runs the hook `jtsx-typescript-mode-hook', as the final or penultimate
step during initialization.

\\{jtsx-typescript-mode-map}" t)
(autoload 'jtsx-install-treesit-language "jtsx"
"Wrapper around `treesit-install-language-grammar' with preset sources.
TS-LANG-KEY is the language to be installed.

(fn TS-LANG-KEY)" t)
(register-definition-prefixes "jtsx" '("jtsx-"))

;;; End of scraped data

(provide 'jtsx-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jtsx-autoloads.el ends here
